# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'audio_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_audioDialog(object):
    def setupUi(self, audioDialog):
        audioDialog.setObjectName("audioDialog")
        audioDialog.resize(777, 482)
        self.out_text = QtWidgets.QTextBrowser(audioDialog)
        self.out_text.setGeometry(QtCore.QRect(50, 20, 681, 221))
        self.out_text.setStyleSheet("font: 16pt \"Consolas\";")
        self.out_text.setObjectName("out_text")
        self.startButton = QtWidgets.QPushButton(audioDialog)
        self.startButton.setGeometry(QtCore.QRect(190, 370, 151, 61))
        self.startButton.setStyleSheet("font: 16pt \"楷体\";")
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(audioDialog)
        self.stopButton.setGeometry(QtCore.QRect(420, 370, 151, 61))
        self.stopButton.setStyleSheet("font: 16pt \"楷体\";")
        self.stopButton.setObjectName("stopButton")
        self.label = QtWidgets.QLabel(audioDialog)
        self.label.setGeometry(QtCore.QRect(180, 280, 411, 61))
        self.label.setStyleSheet("font: 18pt \"黑体\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(audioDialog)
        QtCore.QMetaObject.connectSlotsByName(audioDialog)

    def retranslateUi(self, audioDialog):
        _translate = QtCore.QCoreApplication.translate
        audioDialog.setWindowTitle(_translate("audioDialog", "Dialog"))
        self.startButton.setText(_translate("audioDialog", "开始录制"))
        self.stopButton.setText(_translate("audioDialog", "停止录制"))
        self.label.setText(_translate("audioDialog", "尚未录制"))
