# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(664, 522)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_translate = QtWidgets.QPushButton(self.centralwidget)
        self.input_translate.setGeometry(QtCore.QRect(70, 210, 241, 81))
        self.input_translate.setStyleSheet("font: 16pt \"楷体\";")
        self.input_translate.setObjectName("input_translate")
        self.pic_translate = QtWidgets.QPushButton(self.centralwidget)
        self.pic_translate.setGeometry(QtCore.QRect(70, 380, 241, 81))
        self.pic_translate.setStyleSheet("font: 16pt \"楷体\";")
        self.pic_translate.setObjectName("pic_translate")
        self.identify_translate = QtWidgets.QPushButton(self.centralwidget)
        self.identify_translate.setGeometry(QtCore.QRect(370, 210, 231, 81))
        self.identify_translate.setStyleSheet("font: 16pt \"楷体\";")
        self.identify_translate.setObjectName("identify_translate")
        self.file_translate = QtWidgets.QPushButton(self.centralwidget)
        self.file_translate.setGeometry(QtCore.QRect(370, 380, 231, 81))
        self.file_translate.setStyleSheet("font: 16pt \"楷体\";")
        self.file_translate.setObjectName("file_translate")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 10, 431, 91))
        self.label.setStyleSheet("font: 30pt \"华光行楷_CNKI\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(350, 130, 101, 31))
        self.comboBox.setStyleSheet("font: 14pt \"楷体\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 130, 91, 31))
        self.label_2.setStyleSheet("font: 14pt \"楷体\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(580, 50, 72, 31))
        self.label_3.setStyleSheet("font: 14pt \"黑体\";")
        self.label_3.setObjectName("label_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(560, 90, 93, 28))
        self.pushButton_5.setStyleSheet("font: 10pt \"楷体\";")
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.input_translate.setText(_translate("MainWindow", "输入翻译"))
        self.pic_translate.setText(_translate("MainWindow", "图像目标翻译"))
        self.identify_translate.setText(_translate("MainWindow", "智能识物翻译"))
        self.file_translate.setText(_translate("MainWindow", "文档扫描翻译"))
        self.label.setText(_translate("MainWindow", "易点智能翻译系统"))
        self.comboBox.setItemText(0, _translate("MainWindow", "中译英"))
        self.comboBox.setItemText(1, _translate("MainWindow", "英译中"))
        self.label_2.setText(_translate("MainWindow", "模式"))
        self.label_3.setText(_translate("MainWindow", "V1.0"))
        self.pushButton_5.setText(_translate("MainWindow", "用户管理"))
