# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'picture_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_picDialog(object):
    def setupUi(self, picDialog):
        picDialog.setObjectName("picDialog")
        picDialog.resize(827, 603)
        self.picLabel = QtWidgets.QLabel(picDialog)
        self.picLabel.setGeometry(QtCore.QRect(290, 50, 500, 400))
        self.picLabel.setText("")
        self.picLabel.setWordWrap(True)
        self.picLabel.setObjectName("picLabel")
        self.identifyButton = QtWidgets.QPushButton(picDialog)
        self.identifyButton.setGeometry(QtCore.QRect(60, 310, 191, 61))
        self.identifyButton.setStyleSheet("font: 16pt \"楷体\";")
        self.identifyButton.setObjectName("identifyButton")
        self.loadButton = QtWidgets.QPushButton(picDialog)
        self.loadButton.setGeometry(QtCore.QRect(60, 130, 191, 61))
        self.loadButton.setStyleSheet("font: 16pt \"楷体\";")
        self.loadButton.setObjectName("loadButton")
        self.resultView = QtWidgets.QTableView(picDialog)
        self.resultView.setGeometry(QtCore.QRect(40, 500, 751, 81))
        self.resultView.setStyleSheet("font: 16pt \"Consolas\";")
        self.resultView.setObjectName("resultView")
        self.resultView.horizontalHeader().setVisible(False)

        self.retranslateUi(picDialog)
        QtCore.QMetaObject.connectSlotsByName(picDialog)

    def retranslateUi(self, picDialog):
        _translate = QtCore.QCoreApplication.translate
        picDialog.setWindowTitle(_translate("picDialog", "Dialog"))
        self.identifyButton.setText(_translate("picDialog", "智能识图翻译"))
        self.loadButton.setText(_translate("picDialog", "加载识别图片"))
