# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_searchDialog(object):
    def setupUi(self, searchDialog):
        searchDialog.setObjectName("searchDialog")
        searchDialog.resize(803, 779)
        self.picLabel = QtWidgets.QLabel(searchDialog)
        self.picLabel.setGeometry(QtCore.QRect(50, 60, 700, 500))
        self.picLabel.setText("")
        self.picLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.picLabel.setWordWrap(True)
        self.picLabel.setObjectName("picLabel")
        self.inout = QtWidgets.QLineEdit(searchDialog)
        self.inout.setGeometry(QtCore.QRect(150, 660, 311, 41))
        self.inout.setStyleSheet("font: 16pt \"Consolas\";")
        self.inout.setObjectName("inout")
        self.searchButton = QtWidgets.QPushButton(searchDialog)
        self.searchButton.setGeometry(QtCore.QRect(550, 660, 161, 41))
        self.searchButton.setStyleSheet("font: 16pt \"楷体\";")
        self.searchButton.setObjectName("searchButton")
        self.label = QtWidgets.QLabel(searchDialog)
        self.label.setGeometry(QtCore.QRect(80, 580, 651, 51))
        self.label.setStyleSheet("font: 16pt \"Consolas\";")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(searchDialog)
        QtCore.QMetaObject.connectSlotsByName(searchDialog)

    def retranslateUi(self, searchDialog):
        _translate = QtCore.QCoreApplication.translate
        searchDialog.setWindowTitle(_translate("searchDialog", "Dialog"))
        self.searchButton.setText(_translate("searchDialog", "搜索图片"))
